export const GET_TOTAL_SUM = 'GET_TOTAL_SUM';
export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
export const GET_CHECK_ALL = 'GET_CHECK_ALL';

export const SET_CHECKED_ITEM_MUTATION = 'SET_CHECKED_ITEM_MUTATION';
export const SET_CHECK_ALL_ITEMS_MUTATION = 'SET_CHECK_ALL_ITEMS_MUTATION';
export const ADD_PRODUCT_ITEM_MUTATION = 'ADD_PRODUCT_ITEM_MUTATION';
export const DELETE_PRODUCT_ITEM_MUTATION = 'DELETE_PRODUCT_ITEM_MUTATION';
export const SET_PRODUCTS_LOCAL_STORAGE_MUTATION = 'SET_PRODUCTS_LOCAL_STORAGE_MUTATION';

export const SET_CHECKED_ITEM_ACTION = 'SET_CHECKED_ITEM_ACTION';
export const SET_CHECK_ALL_ITEMS_ACTION = 'SET_CHECK_ALL_ITEMS_ACTION';
export const ADD_PRODUCT_ITEM_ACTION = 'ADD_PRODUCT_ITEM_ACTION';
export const DELETE_PRODUCT_ITEM_ACTION = 'DELETE_PRODUCT_ITEM_ACTION';
export const CHECK_ITEM_LOCAL_STORAGE_ACTION = 'CHECK_ITEM_LOCAL_STORAGE_ACTION';